### ISSUE TITLE
Missing metric oracledb_recovery

### ISSUE THREAD

**Issue by djvl** [freenetdigital/prometheus_oracle_exporter#26]
Hi, first of all I want to thank you for this very useful exporter.

Since the upgrade from 1.1.1 to 1.1.2 one metric does not work anymore for me as seen below.

1.1.1:
```
# curl -s http://localhost:9161/metrics |grep oracledb_recovery
# HELP oracledb_recovery Gauge metric with percentage usage of FRA (v$recovery_file_dest).
# TYPE oracledb_recovery gauge
oracledb_recovery{database="mivudb",dbinstance="mivudb",type="percent_space_reclaimable"} 1.39
oracledb_recovery{database="mivudb",dbinstance="mivudb",type="percent_space_used"} 16.63
#
```
1.1.2:
```
# curl -s http://localhost:9161/metrics |grep oracledb_recovery
#
```
All other metrics are presenting values when using the 1.1.2 version.

I make use of the precompiled binaries from the release page.

Specs: RHEL7 and Oracle 11gR2

**Comment by floyd871** [comment]
Yes, you are right. I have removed it from the "Fast" Queries Section. Our Hoster, which also manages our DBs complains about high I/O on ASM Instance because of this Query. So i moved it to the extended section. Use one of the Parameters:

params:
tablerows: [true]
lobbytes: [true]
tablebytes: [true]
indexbytes: [true]

**Comment by bastischubert** [comment]
well than you should at least update the readme.md and remove it from the default section - and maybe add a param for explicit collection of the metrics instead of "magic conjunctions" ;)
